version: '3'
services:
  web:
    build:
      context: src/frontend
    container_name: web
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - MODEL_FILE=/data/model.pkl
    ports:
      - 5000:5000
    volumes:
      - data:/data
      - ${PWD}/healthchecks:/healthchecks
    depends_on:
      model:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "/healthchecks/ping.py http://localhost:5000 || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 3s
  model:
    build:
      context: src/model
    command:
      - /prices.csv
    container_name: model
    volumes:
      - ${PWD}/data/prices.csv:/prices.csv:ro
      - data:/data
    environment:
      - MODEL_FILE=/data/model.pkl
  test:
    build:
      context: src/client
    container_name: test
    environment:
      - API_URL=http://web:5000/api
    depends_on:
      web:
        condition: service_healthy
volumes:
  data:
    name: model-data
