---
apiVersion: v1
kind: Service
metadata:
  name: ml-house-pricing-web
  labels:
    app: web
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web
  selector:
    app: web
  type: ClusterIP   # LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/atrakic/ml-house-pricing-web:latest
          imagePullPolicy: Always # IfNotPresent
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: PORT
              value: "8080"
            - name: MODEL_FILE
              value: "/opt/model.pkl"
          volumeMounts:
            - name: data
              mountPath: /opt
          #livenessProbe:
          #  exec:
          #    command:
          #    - ls
          #    - $MODEL_FILE
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              httpHeaders:
                - name: X-Custom-Header
                  value: Probe
            initialDelaySeconds: 10
            timeoutSeconds: 5
      initContainers:
        # First we need to create model and serialise data on file
        - name: init
          image: ghcr.io/atrakic/ml-house-pricing-model:latest
          imagePullPolicy: Always # IfNotPresent
          # command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
          env:
            - name: MODEL_FILE
              value: /opt/model.pkl
            - name: CSV_FILE
              value: "https://raw.githubusercontent.com/atrakic/ml-model-house-pricing/main/data/prices.csv"
      volumes:
        - name: data
          emptyDir: {}
